name: MATLAB Windows OutOfProcess Bug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: 'windows-latest'
    env:
      mhkit-python-dir: 'MHKiT-Python'
    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run Python
        run: python -c "print('Hello World!')"
      - name: Create MATLAB batch command
        shell: bash
        run: echo "COMMAND=pyenv('ExecutionMode', 'OutOfProcess')" >> "$GITHUB_ENV"
      - name: Run command
        run: matlab -batch "${{ env.COMMAND }}"
      - name: Create MATLAB batch command
        shell: bash
        run: echo "COMMAND=pyenv('ExecutionMode', 'OutOfProcess'),
          py.list({'Monday','Tuesday','Wednesday','Thursday','Friday'})" >> "$GITHUB_ENV"
      - name: Run command
        run: matlab -batch "${{ env.COMMAND }}"

